-- MySQL Script generated by MySQL Workbench
-- 11/07/20 12:35:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema railways
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema railways
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railways` DEFAULT CHARACTER SET utf8 ;
USE `railways` ;

-- -----------------------------------------------------
-- Table `railways`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`trains` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`roads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`roads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`travels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`travels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departure_time` VARCHAR(45) NULL,
  `departure_date` DATE NULL,
  `arrival_time` VARCHAR(45) NULL,
  `arrival_date` DATE NULL,
  `road_id` INT NOT NULL,
  `train_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travels_roads1_idx` (`road_id` ASC),
  INDEX `fk_travels_trains1_idx` (`train_id` ASC),
  CONSTRAINT `fk_travels_roads1`
    FOREIGN KEY (`road_id`)
    REFERENCES `railways`.`roads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travels_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `railways`.`trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`stations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `city_id` INT NOT NULL,
  `road_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stations_cities_idx` (`city_id` ASC),
  INDEX `fk_stations_roads1_idx` (`road_id` ASC),
  CONSTRAINT `fk_stations_cities`
    FOREIGN KEY (`city_id`)
    REFERENCES `railways`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stations_roads1`
    FOREIGN KEY (`road_id`)
    REFERENCES `railways`.`roads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`class_train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`class_train` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NOT NULL,
  `train_id` INT NOT NULL,
  `ticket_price` FLOAT NULL DEFAULT 0,
  `seats` INT NULL DEFAULT 0,
  INDEX `fk_classes_has_trains_trains1_idx` (`train_id` ASC),
  INDEX `fk_classes_has_trains_classes1_idx` (`class_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_classes_has_trains_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `railways`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_trains_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `railways`.`trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`passengers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` TEXT NULL,
  `phone` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat` INT NULL DEFAULT 0,
  `price` FLOAT NULL,
  `passenger_id` INT NOT NULL,
  `travel_id` INT NOT NULL,
  `train_id` INT NOT NULL,
  `class_train_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_passengers1_idx` (`passenger_id` ASC),
  INDEX `fk_tickets_travels1_idx` (`travel_id` ASC),
  INDEX `fk_tickets_trains1_idx` (`train_id` ASC),
  INDEX `fk_tickets_class_train1_idx` (`class_train_id` ASC),
  CONSTRAINT `fk_tickets_passengers1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `railways`.`passengers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_travels1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `railways`.`travels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `railways`.`trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_class_train1`
    FOREIGN KEY (`class_train_id`)
    REFERENCES `railways`.`class_train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railways`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railways`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
